function amplificator(R,A,f,E,Ptot,VBE,tip, chec2d, chec3d)


fig=figure('Name','interfata',...
     'Units','normalized',...
     'Position',[0.1 0.1 0.8 0.8],...
     'NumberTitle','off',...
     'Color',[145/255 140/255 141/255]);
% ------TITLU------------------------------------------------------
 uicontrol('Style', 'text',...
                'Units', 'normalized',...
                'BackgroundColor',[145/255 140/255 141/255],...
                'ForegroundColor','black',...
                'Position',[0.05 0.89 0.4 0.1],...
                'String', 'Amplificator de putere clasa B',...
                'Fontsize', 17,...
                'HorizontalAlignment','center');
%-------SWITCH PENTRU FRECVENTA--------------------------------------------
switch(tip)
    case 1
        f=10;
    case 2
        f=15;

    case 3
        f=25;
    case 4
        f=75;
    case 5
        f=100;
    case 6
        f=250;
    case 7
        f=499;
        
        
end
%------SEMNALE-------------------------------------------------------------
 T = 1 / f;
 t = -0.1:1/(f*100) : 0.1;
 vi=A*sin(2*pi*f*t);
 vo=A*sin(2*pi*f*t);
 %----CALCULE PUTERE & RANDAMENT-------------------------------------------
 Ptot=(2*E*A)/(pi*R);
 PT=((E*A)/(pi*R)-(A*A)/(4*R));
 Pmed=(A*A)/(2*R);
 ran=(pi*A)/(4*E);
 %----CONDITIE PENTRU TENSIUNEA DE IESIRE----------------------------------
 for i=1:length(t)
 if vo(i)<-VBE
 vo(i)=vi(i)-VBE;
 elseif vi(i)>VBE
     vo(i)=vi(i)+VBE;
 else
     vo(i)=0;

 end
 end
%------IMAGINE-------------------------------------------------------------
 img = imread('poza2.jpg');
image(img);
x = 0;
y = 0;
width = 0.3;
height = 0.5;
set(gca,'units','normalized','position',[x y width height])
%-----AFISARE SEMNALE------------------------------------------------------
subplot('Position',[0.35 0.3 0.6 0.2]);
plot(t,vi,'b');
hold on;
xlabel('Timp[s]')
ylabel('Amplitudine[V]');
title('Tensiunea de intrare');
ax=gca;
ax.TitleHorizontalAlignment = 'right';
legend('vi');
subplot('Position',[0.35 0.05 0.6 0.2]);
plot(t,vo,'r');
hold on;
ylabel('Amplitudine[V]');
xlabel('Timp[s]')
legend('vo');
title('Tensiunea de iesire');
ax=gca;
ax.TitleHorizontalAlignment = 'right';
%------BUTON PENTRU IESIRE-------------------------------------------------
Iesire=uicontrol('Style','pushbutton',...
                  'Units','normalized',...
                  'Position',[0.8 0.9 0.14 0.05],...
                  'backgroundcolor','k',...
                  'foregroundcolor','w',...
                  'Fontsize',12,...
                  'String','Iesire',...
                  'FontWeight','bold',...
                  'Tag','iesire',...
                  'TooltipString','Apãsati butonul pentru a iesi din program.',...
                  'Callback','close');
%-----BUTON PRENTRU REVENIREA LA INCEPUT-----------------------------------
uicontrol('Style','pushbutton',... 
 'Units','normalized',...
 'Position',[0.6 0.9 0.14 0.05],...
 'FontSize',12,...
 'backgroundcolor', 'k',...
'foregroundcolor','white',...
 'FontWeight','bold',...
 'string','Pagina principala',...
 'TooltipString','Apasati butonul pentru te reintorece la pagina principala',...
 'Callback','close; Inceput');
%---RADIOGROUP & RADIOGROUPB-----------------------------------------------
RadioGroup=uibuttongroup('Visible','on',...
 'BackgroundColor',[145/255 140/255 141/255],...
'ForegroundColor','black',...
 'Title','Parametrii',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.02 0.55 0.25 0.4]); 
RadioGroupB=uibuttongroup('Visible','on',...
 'BackgroundColor',[145/255 140/255 141/255],...
'ForegroundColor','black',...
 'Title','Rezultate',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.3 0.55 0.25 0.4]); 
%-------PUTEREA TOTALA-----------------------------------------------------
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.2 0.75 0.2 0.15],...
'backgroundcolor',[145/255 140/255 141/255],...
'foregroundcolor','black',...
'fontweight','bold',...
 'fontsize',12,...
'String','Puterea totala[W]',...
'Parent',RadioGroupB);
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.5 0.75 0.2 0.15],...
 'backgroundcolor',[145/255 140/255 141/255],...
 'fontsize',12,...
 'foregroundcolor','b',...
 'String',Ptot,...
'Parent',RadioGroupB); 
%---PUTEREA PE TRANZISTOR--------------------------------------------------
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.2 0.55 0.2 0.15],...
'backgroundcolor',[145/255 140/255 141/255],...
'foregroundcolor','black',...
'fontweight','bold',...
'fontsize',12,...
'String','Puterea T1=T2[W]',...
'Parent',RadioGroupB);
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.5 0.55 0.2 0.15],...
 'backgroundcolor',[145/255 140/255 141/255],...
 'fontsize',12,...
 'foregroundcolor','b',...
 'String',PT,...
'Parent',RadioGroupB); 
%----PUTEREA MEDIE---------------------------------------------------------
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.2 0.35 0.2 0.15],...
'backgroundcolor',[145/255 140/255 141/255],...
'foregroundcolor','black',...
'fontsize',12,...
'fontweight','bold',...
'String','Puterea medie[W]',...
'Parent',RadioGroupB);
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.5 0.35 0.2 0.15],...
 'backgroundcolor',[145/255 140/255 141/255],...
 'fontsize',12,...
 'foregroundcolor','b',...
 'String',Pmed,...
'Parent',RadioGroupB); 
%-------------RANDAMENTUL--------------------------------------------------
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.2 0.15 0.2 0.15],...
'backgroundcolor',[145/255 140/255 141/255],...
'foregroundcolor','black',...
'fontweight','bold',...
'fontsize',12,...
'String','Randamentul[%]',...
'Parent',RadioGroupB);
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.5 0.15 0.2 0.15],...
 'backgroundcolor',[145/255 140/255 141/255],...
 'fontsize',12,...
 'foregroundcolor','b',...
 'String',ran,...
'Parent',RadioGroupB); 
%--------AMPLITUDINE-------------------------------------------------------
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.80 0.2 0.1],...
'fontweight','bold',...
'fontsize',12,...
'backgroundcolor',[145/255 140/255 141/255],...
'foregroundcolor','black',...
'String','A[V]',...
'Parent',RadioGroup);

uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.25 0.80 0.2 0.1],...
'foregroundcolor','b',...
'backgroundcolor',[145/255 140/255 141/255],...
'String',num2str(A),...
'Callback','A = str2num(get(gco,''String''));close,amplificator(R,A,f,E,Ptot,VBE,tip)',...
'Parent',RadioGroup);
%-----------REZISTENTA-----------------------------------------------------
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.65 0.2 0.1],...
'fontweight','bold',...
'backgroundcolor',[145/255 140/255 141/255],...
'fontsize',12,...
'foregroundcolor','k',...
'String','R[ohm]',...
'Parent',RadioGroup);

uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.25 0.65 0.2 0.1],...
'foregroundcolor','b',...
'backgroundcolor',[145/255 140/255 141/255],...
'String',num2str(R),...
'Callback','R = str2num(get(gco,''String''));close,amplificator(R,A,f,E,Ptot,VBE,tip)',...
'Parent',RadioGroup);
%---------------E----------------------------------------------------------
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.50 0.2 0.1],...
'backgroundcolor',[145/255 140/255 141/255],...
'fontweight','bold',...
'fontsize',12,...
'foregroundcolor','black',...
'String','E[V]',...
'Parent',RadioGroup);

uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.25 0.50 0.2 0.1],...
'foregroundcolor','b',...
'backgroundcolor',[145/255 140/255 141/255],...
'String',num2str(E),...
'Callback','E = str2num(get(gco,''String''));close,amplificator(R,A,f,E,Ptot,VBE,tip)',...
'Parent',RadioGroup);
%-----FRECVENTA------------------------------------------------------------
Bp_u=uicontrol('Style','PopupMenu',...
 'Units','normalized',...
 'Position',[0.4 0.15 0.2 0.1],...
 'value',tip,...
 'backgroundcolor',[145/255 140/255 141/255],...
 'foregroundcolor','b',...
 'String','10|15|25|75|100|250|500',...
 'Callback','tip=get(gco,''value'');close;amplificator(R,A,f,E,Ptot,VBE,tip)',...
'Parent',RadioGroup);
         
          f_text=uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.1 0.15 0.3 0.1],...
        'backgroundcolor',[145/255 140/255 141/255],...
        'foregroundcolor','black',...
        'fontweight','bold',...
        'fontsize',12,...
        'String','Frecventa[Hz]',...
    'Parent',RadioGroup); 
%--------RADIOBUTTON-------------------------------------------------------
Br=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.6 0.7 .3 .15],...
 'String','2D',...
 'Callback',' semnal2d(f, A)',...
 'backgroundcolor',[145/255 140/255 141/255],...
        'foregroundcolor','black',...
        'fontweight','bold',...
        'fontsize',12,...
'Parent',RadioGroup) ;

Br1=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.6 0.5 .3 .15],...
 'String','3D',...
 'Callback','semnal3d(f, A)',...
 'backgroundcolor',[145/255 140/255 141/255],...
        'foregroundcolor','black',...
        'fontweight','bold',...
        'fontsize',12,...
'Parent',RadioGroup) ; 
% Br1=uicontrol('Style','radiobutton',...
%  'Units','normalized',...
%  'Position',[0.6 0.3 .3 .15],...
%  'String','CSTV',...
%  'Callback','semnal3d(f, A)',...
%  'backgroundcolor',[145/255 140/255 141/255],...
%         'foregroundcolor','black',...
%         'fontweight','bold',...
%         'fontsize',12,...
% 'Parent',RadioGroup) ; 
%------CHECKBOX------------------------------------------------------------
% Bc_b1=uicontrol('Style','Checkbox',...
%  'Units','normalized',...
%  'String','VO<->VI',...
%  'BackgroundColor','r',...
%  'Position', [0.1 .3 .3 .1],...
%  'Callback',,...
%  'backgroundcolor',[145/255 140/255 141/255],...
%  'foregroundcolor','black',...
%  'fontweight','bold',...
%  'fontsize',12,...
% 'Parent',RadioGroup);


 

















