clear all;
close all;
Fig=figure('Name','Laborator Grafica',...
           'Units','normalized',...
           'Position',[0.1 0.1 0.8 0.8],...
           'NumberTitle','off','color',[0.75,0.75,0.75]);
       uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.0 0.95 0.08 0.05],...
    'FontSize',12,...
    'backgroundcolor', 'k',...
'foregroundcolor','white',...
 'FontWeight','bold',...
 'String','Iesire',...
 'Callback','close');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.0 0.85 0.08 0.05],...
    'FontSize',12,...
    'backgroundcolor', 'k',...
'foregroundcolor','white',...
 'FontWeight','bold',...
 'String','BIBLIOGRAFIE',...
 'Callback','open(''bibliografie.html'')');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.0 0.75 0.08 0.05],...
    'FontSize',12,...
    'backgroundcolor', 'k',...
'foregroundcolor','white',...
 'FontWeight','bold',...
 'String','AUTOR',...
 'Callback','open(''Autor.docx'')');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.0 0.65 0.08 0.05],...
    'FontSize',12,...
    'backgroundcolor', 'k',...
'foregroundcolor','white',...
 'FontWeight','bold',...
 'String','TEORIE',...
 'Callback','open(''teorie.docx'')');
       w=imread('fundal.jpg');
                image(w);
                set(gca,'Position',[0 0 1 1]);
                axis off; 
                f=uimenu('Label','Documentatie');
           uimenu(f,'Label','Prima Pagina','Callback','Inceput');
           uimenu(f,'Label','Autor','Callback','Autor');
           uimenu(f,'Label','Teorie','Callback','open(''Teorie.docx'')');
           uimenu(f,'Label','Bibliografie','Callback','open(''Bibliografie.html'')');
           uimenu(f,'Label','Iesire','Callback','close',...
                    'Separator','on','Accelerator','Q');
                uicontrol('Style','text','FontSize',16,...
                                    'Units','normalized',...
                                    'Position',[0.05 0.1 0.9 0.05],...
                                    'background','k',...
                                    'foregroundcolor','w',...
                                   'String', ' Vanca Rafael Marian               Grupa 2121 ');
                                               
                                hbsp = uicontrol('String','Amplificator de putere clasa B','FontSize',20,...
                             'Units','normalized',...
                             'background','k',...
                             'foregroundcolor','w',...
                             'Position',[.3 .4 .4 .25],...
                             'Callback', 'start' );
                                   
                              